/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.libraryproject;

import java.sql.*;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

public class JFrameBookUser extends javax.swing.JFrame {

    
    public JFrameBookUser() {
        initComponents();
        this.setTitle("Сдать книгу"); //Название на верху формы
        try {
            Class.forName("org.postgresql.Driver");
            String conToDb = "jdbc:postgresql://localhost:5432/libraryproject";
            connection = (Connection)DriverManager.getConnection(conToDb, "postgres", "qwerty1234");
            connection.setAutoCommit(true);
            statement = (Statement) connection.createStatement();
            System.out.println("success");
            
            //заполнение комбобокса, выводящего список людей, из БД
            resultSet = statement.executeQuery("SELECT user_id, user_name FROM userlist");
            while (resultSet.next()) {
                jComboUserBookList2.addItem(resultSet.getInt("user_id") + ". " + resultSet.getString("user_name"));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JFrameBookUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameBookUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListUserBook = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jComboUserBookList2 = new javax.swing.JComboBox<>();
        jButtonShow = new javax.swing.JButton();
        jButtonPassBook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Книги");

        jScrollPane2.setViewportView(jListUserBook);

        jLabel2.setText("Читатель");

        jComboUserBookList2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jComboUserBookList2AncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jComboUserBookList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboUserBookList2ActionPerformed(evt);
            }
        });

        jButtonShow.setText("Показать");
        jButtonShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowActionPerformed(evt);
            }
        });

        jButtonPassBook.setText("Сдать в библиотеку");
        jButtonPassBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPassBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboUserBookList2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPassBook, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboUserBookList2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButtonShow, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButtonPassBook, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboUserBookList2AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboUserBookList2AncestorMoved
        
    }//GEN-LAST:event_jComboUserBookList2AncestorMoved

    private void jComboUserBookList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboUserBookList2ActionPerformed
        
    }//GEN-LAST:event_jComboUserBookList2ActionPerformed

    private void jButtonShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowActionPerformed
        //выводит список книг, которые взял человек, выбранный в комбобоксе(список людей)
        lineForDelete = jComboUserBookList2.getSelectedItem().toString();
        strTokenizer = new StringTokenizer(lineForDelete, ".");
        idDelete = strTokenizer.nextToken();
        try {
            resultSet2 = statement.executeQuery("SELECT book_id, book_name FROM booklist WHERE book_id IN (SELECT fk_book_id FROM uoblist WHERE fk_user_id = " + idDelete + ")");
            defList = new DefaultListModel();
            while (resultSet2.next()) {
                defList.addElement(resultSet2.getInt("book_id") + "." + resultSet2.getString("book_name"));
            }
            jListUserBook.setModel(defList);
            resultSet2.close();
        } catch (SQLException ex) {
            Logger.getLogger(JFrameBookUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonShowActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //закрытие подключений к БД
        try {
            System.out.println("close");
            connection.close();
            statement.close();
            resultSet.close();
        } catch (SQLException ex) {
            Logger.getLogger(JFrameBookUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    private void jButtonPassBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPassBookActionPerformed
        //метод для сдачи книжки конкретным пользователем
        try {
            lineForDelete = jListUserBook.getSelectedValue();
            strTokenizer = new StringTokenizer(lineForDelete, ".");
            idDelete = strTokenizer.nextToken();
            statement.executeUpdate("DELETE FROM uoblist WHERE fk_book_id = " + idDelete); //удаляем из таблицы (человек - взятая книга) строку с книгой, которую мы сдаем
            statement.executeUpdate("UPDATE booklist SET book_in_lib = true WHERE book_id = " + idDelete); //меняем поле book_in_lib(книга в библиотеке?) на true, так как книгу сдаем обратно в библиотеку
            defList.remove(jListUserBook.getSelectedIndex());
        } catch (SQLException ex) {
            Logger.getLogger(JFrameBookUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPassBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameBookUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameBookUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameBookUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameBookUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameBookUser().setVisible(true);
            }
        });
    }

    Connection connection = null;
    Statement statement = null;
    ResultSet resultSet = null;
    ResultSet resultSet2 = null;
    
    DefaultListModel defList = null; // класс, используемый ждя заполнения листа данными
    
    StringTokenizer strTokenizer = null; //класс для разделения строки
    
    String idDelete = "";//переменная для айди книги или человека, с помощью этой переменной делаем запрос в БД для удаления книги или человека из соответствующей таблицы
    String lineForDelete = "";//переменная для строки, которую мы разделяем на части с помощью StringTokenizer
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPassBook;
    private javax.swing.JButton jButtonShow;
    private javax.swing.JComboBox<String> jComboUserBookList2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListUserBook;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
